// lib/firebase_options.dart
// ─────────────────────────────────────────────────────────────────────────────
// PLACEHOLDER — Replace this file with the one generated by the FlutterFire CLI:
//   flutter pub global activate flutterfire_cli
//   flutterfire configure
//
// That will generate a real firebase_options.dart with your actual project IDs.
// ─────────────────────────────────────────────────────────────────────────────
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform: $defaultTargetPlatform');
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_API_KEY'),
    appId: dotenv.get('FIREBASE_WEB_APP_ID'),
    messagingSenderId: dotenv.get('FIREBASE_WEB_MESSAGING_SENDER_ID'),
    projectId: dotenv.get('FIREBASE_WEB_PROJECT_ID'),
    authDomain: dotenv.get('FIREBASE_WEB_AUTH_DOMAIN'),
    storageBucket: dotenv.get('FIREBASE_WEB_STORAGE_BUCKET'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY'),
    appId: dotenv.get('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: dotenv.get('FIREBASE_WEB_MESSAGING_SENDER_ID'),
    projectId: dotenv.get('FIREBASE_WEB_PROJECT_ID'),
    storageBucket: dotenv.get('FIREBASE_WEB_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
    appId: dotenv.get('FIREBASE_IOS_APP_ID'),
    messagingSenderId: dotenv.get('FIREBASE_WEB_MESSAGING_SENDER_ID'),
    projectId: dotenv.get('FIREBASE_WEB_PROJECT_ID'),
    storageBucket: dotenv.get('FIREBASE_WEB_STORAGE_BUCKET'),
    iosClientId: dotenv.get('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: dotenv.get('FIREBASE_IOS_BUNDLE_ID'),
  );
}